import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import GetDB from '../components/app'
import Link from 'next/link'
import { BadEnd } from './bad'
import { TrueEnd } from './true'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Link href="/true"><a>TrueEnd</a></Link>
        <Link href="/good"><a>GoodEnd</a></Link>
        <Link href="/bad"><a>BadEnd</a></Link>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

      </main>


    </div>
  )
}
